baseURL: 'https://hugo-theme-hibi.netlify.app/'
languageCode: 'ja'
hasCJKLanguage: true
summaryLength: 100
title: '日々'
pagination:
  pagerSize: 10
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: Archives
      name: archives
      url: /archives/
      weight: 20
    - identifier: About
      name: about
      url: /about/
      weight: 30
params:
  #タグ未設定の記事に付与するタグ
  tagFallbackLabel: 日常
  headerSubtitle: Hibi
imaging:
  quality: 80
  resampleFilter: lanczos
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: true
permalinks:
  posts: /posts/:slug/
