[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.146.5"
  HUGO_ENV = "production"
  # Hugo extended version is needed for PostCSS/Tailwind
  HUGO_EXTENDED = "true"

[context.production.environment]
  HUGO_ENV = "production"

# Production deploys from the main branch
[context.production]
  command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
